<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdae7c3829e148cbc31452d43791afdcb
{
    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PHPExcel' => 
            array (
                0 => __DIR__ . '/..' . '/phpoffice/phpexcel/Classes',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInitdae7c3829e148cbc31452d43791afdcb::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitdae7c3829e148cbc31452d43791afdcb::$classMap;

        }, null, ClassLoader::class);
    }
}
